name: Vérification des objets Snowflake dans les fichiers SQL

on:
  push:
    branches:
      - '*'
    paths:
      - 'migrations/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: |
          sudo apt-get install -y python3-pip
          pip3 install snowflake-connector-python

      - name: Vérification des fichiers SQL
        run: |
          for file in $(find ./migrations -type f -name '*.sql'); do
            echo "Vérification des objets Snowflake dans le fichier $file"
            # Récupération des créations d'objets
            creations=$(grep -E "CREATE\s+(OR\s+REPLACE\s+)?(TABLE|VIEW|PROCEDURE|FUNCTION|SEQUENCE)\s+[A-Za-z0-9_]+\s*\(?" $file)
            # Affichage des résultats
            if [[ -n "$creations" ]]; then
              echo "$creations"
              echo "Le fichier $file contient des objets Snowflake valides."
            else
              echo "ERREUR: Le fichier $file ne contient pas d'objets Snowflake valides."
              exit 1
            fi
          done